In [1]:
!python -m pip install numpy

In [2]:
import numpy as np

In [3]:
num_list = [1, 2, 3, 4]

int_arr2 = np.array(num_list)
print(int_arr2)

[1 2 3 4]


In [6]:
arr1 = np.arange(0,10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr2 = np.arange(0, 10, 2)
arr2

array([0, 2, 4, 6, 8])

In [8]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [18]:
#한 가지 데이터타입으로 통일되어야 한다

list_data = ['1', 2, '3']
arr4 = np.array(list_data)
arr4

array(['1', '2', '3'], dtype='<U21')

In [19]:
list_data2 = [1, 2., 3]
arr5 = np.array(list_data2)
arr5

array([1., 2., 3.])

In [22]:
temp6 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr6 = np.array(temp6)
print(arr6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
print(temp6)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [24]:
print(type(temp6))
print(type(arr6))

<class 'list'>
<class 'numpy.ndarray'>


In [26]:
#3차원 이상의 배열은 tensor라 한다

arr7 = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]], [[17,18,19,20], [21,22,23,24]]])
print(arr7)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [33]:
arrx = np.array([1,2,3,4])
print(arrx)
print(arrx.ndim)
print(arrx.shape)

[1 2 3 4]
1
(4,)


In [34]:
arr8 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr8.ndim)
print(arr8.shape)

arr9 = arr8.reshape(2,5)

print(arr9.ndim)
print(arr9.shape)

1
(10,)
2
(2, 5)


In [35]:
print(arr8)

[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
print(arr9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#10개 요소 있는 거를 3, 3으로 바꾸려 하면 에러가 난다

arr8.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [40]:
arrn = np.array([1,2,3,4,5,6])
arrn1 = arrn.reshape(2,3)
print(arrn1)

[[1 2 3]
 [4 5 6]]


In [41]:
arr10 = arr8.reshape(2, 5, 1)

print(arr10.ndim)
print(arr10.shape)
print(arr10)

3
(2, 5, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


In [42]:
#shape 
#(2,5)와 (2,5,1)은 전혀 다른 numpy array다. 
#shape이 같다면 그 두 개까리 사칙연산 가능하다 (행렬의 느낌...)

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a*b)

[ 4 10 18]


In [43]:
#벡터화 연산

print(a + 1)
print(a - 1)
print(a * 3)
print(a / 2)

[2 3 4]
[0 1 2]
[3 6 9]
[0.5 1.  1.5]


In [55]:
#1부터 10까지 10개의 데이터 생성
#linspace = linear space

arr11 = np.linspace(1, 10, 10)
print(arr11)
print(arr11.dtype)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


In [52]:
arr11 = np.linspace(1, 10, 10, dtype=int)
print(arr11)
print(arr11.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
int64


In [53]:
arr12 = np.linspace(1, np.pi, 10)
print(arr12)
print(arr12.dtype)


[1.         1.23795474 1.47590948 1.71386422 1.95181896 2.1897737
 2.42772844 2.66568318 2.90363791 3.14159265]
float64


In [59]:
#np.zeros 많이 쓴다. np.ones도 많이 쓰고

#0을 10개 만들어준다. 그게 필요할 때가 있다. 
arr13 = np.zeros(10)
print(arr13)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#1을 10개 만들어 준다
arr14 = np.ones(10)
print(arr14)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [62]:
data1 = list(range(0,10))

data2 = []
for x in data1: 
    data2.append(x*2)

data3 = [x*2 for x in data1]
print(data1)
print(data2)
print(data3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [65]:
data4 = np.array(data1)
data5 = 2*data4
print(data5)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
#int타입으로 나온다
data5.dtype

dtype('int64')

In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(2*a+b)
print(a==2)
print(b>10)
print((a==2)&(b>10))

#&은 하나가 false면 false다. 둘 다 True여야 True다. 

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [71]:
c = np.array([[0,1,2],[3,4,5]])
print(c.ndim)
print(c.shape)
print(c)

2
(2, 3)
[[0 1 2]
 [3 4 5]]


In [ ]:
d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
print(d.ndim)
print(d.shape)
print(d)
print(d.size) # 2x3x4 = 요소의 수

3
(2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
24


In [ ]:
a1 = np.array([0, 1, 2, 3, 4])
print(a1[2]) 
print(a1[-1]) #뒤에서 첫번째 

2
4


In [80]:
#0, 1, 5값을 뽑아내주세요 
a2 = np.array([[0, 1, 2], [3, 4, 5]])
print(a2[0,0])
print(a2[0,1])
print(a2[1,2])

0
1
5


In [ ]:
a3 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a3[0][0:4]) 
print(a3[:,1]) #모든 행에서 1열 가져오기 

#a[?,?] = a[?][?]


[0 1 2 3]
[1 5]


In [88]:
print(a3[1,1:4])

[5 6 7]


In [ ]:
print(a3[:,:2]) #모든 행에서 0부터 2이전 자리까지 가져오기

[[0 1]
 [4 5]]


In [ ]:
i = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
False, True, False, True, False])
i[idx] 

#True 위치의 값만 골라 새로운 배열을 만든다 

array([0, 2, 4, 6, 8])

In [100]:
temp7 = i % 2 == 0
print(temp7.shape)
print(temp7)

(10,)
[ True False  True False  True False  True False  True False]


In [105]:
a4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a4[:,[0,3]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [107]:
#위와 다른 방법. 이런 방법도 있다
print(a4[(a4 % 4 == 0) | (a4 % 4 == 1)])

[ 1  4  5  8  9 12]


In [ ]:
a4[2,0:4],a4[0,0:4],a4[1,0:4]
a4[[2,0,1]] #이게 더 간단한 방법이다 

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [113]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#배열에서 3의 배수를 찾아주세요.

k = np.array(list(range(1,21)))
k[k % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [114]:
k[k % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [115]:
k[(k % 3== 0) & (k % 4 == 1)]

array([9])

In [ ]:
#판다스 해보기 
